ministryofjustice/laa-crime-commons

.circleci/config.yml
build.gradle
crime-commons-spring-boot-starter/build.gradle

LCAM-428 Configure SonarCloud

---

build.gradle
crime-commons-samples/src/main/java/uk/gov/justice/laa/crime/samples/config/WebSecurityConfiguration.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/client/RestAPIClientTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-704)
Upgrade Spring Boot version to 3.1.2

Lcam 704: Upgrade Spring Boot version to 3.1.2 for laa-crime-commons

---

crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/filters/WebClientFiltersTest.java

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-709)
After initial look it seemed there were already a few test cases covering the retry mechanism but not one covering the scenario where a call was retried a couple of time but eventually succeeded before hitting the retry limit, so this has been added.

LCAM 709 Unit Tests for Web Client Retry Mechanism

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfigurationTest.java

LCAM-895| removed references to access keys

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfigurationTest.java

LCAM-895| updated conditional property

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java

CMA Client

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfigurationTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1094)
Added WebClients for CCP, CCC and Validation services.

LCAM-1094|Add WebClients for CCP, CCC and Validation services

---

crime-commons-spring-boot-starter-rest-client/build.gradle

Upgrade Sentry Version

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java

Moved to Reactor HTTPClient

---

crime-commons-classes/build.gradle
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/RequestBuilderUtils.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/tracing/TraceIdHandlerTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-11150)
Add missing methods in Request Builder Utils.
Fix sonar code smells.

Add missing methods in Request Builder Utils

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AssessmentType.java

Added missing values

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/CourtType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/DecisionReason.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/DeniedIncomeDetailCode.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/ExtraExpenditureDetailCode.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailCode.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailReason.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewProgressAction.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewProgressResponse.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewStatus.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/RequestType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/ReviewResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/ReviewType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/WorkType.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/CourtTypeTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/DecisionReasonTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/DeniedIncomeDetailCodeTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/ExtraExpenditureDetailCodeTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailCodeTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailReasonTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/HardshipReviewProgressActionTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/HardshipReviewProgressResponseTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/HardshipReviewStatusTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/ReviewResultTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1154)
Moved common enums into common classes module.

Move common enums into common classes module

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/Frequency.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/FrequencyTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1154)

Add description in Frequency

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/client/RestAPIClient.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/client/RestAPIClientTest.java

Added Patch Request

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/client/RestAPIClient.java

Added missing path param

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/client/RestAPIClient.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/client/RestAPIClientTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1095)
Added utility method to build PUT request with path variables

Add utility method to build PUT request with path variables

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/client/RestAPIClient.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/client/RestAPIClientTest.java

Reverts ministryofjustice/laa-crime-commons#63

Revert "Add utility method to build PUT request with path variables"

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailType.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1276)

LCAM-1276|Update the Enum to fix the deserialization issue

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailReason.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/HardshipReviewDetailReasonTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1281)

LCAM-1281|Add method to get review detail reason based on id

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/HardshipReviewStatus.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1281)

Fix the enum deserialisation

---

.circleci/config.yml
build.gradle
crime-commons-classes/build.gradle
crime-commons-spring-boot-starter-rest-client/build.gradle

[LCAM-1285](https://dsdmoj.atlassian.net/browse/LCAM-1285)
- Updated build with semver gradle plugin for multi-module release
- Updated circleci workflows to segregate the release steps crime commons rest client and crime-common-classes 
- updated nexusPublishing to publish snapshot and release versions
[LCAM-1285]: https://dsdmoj.atlassian.net/browse/LCAM-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LCAM-1285: Automate multi-module release workflow for crime commons

---

crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfigurationTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1290)

Added CAT Rest Client

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/DateUtil.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/util/DateUtilTest.java
crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/jackson/ZonedDateTimeDeserializer.java
crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/jackson/ZonedDateTimeDeserializerTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1307)
Added deserialiser to handle Zoned Date Time and associated tests.
Added an utility method to convert LocalDateTime into ZonedDateTime.

LCAM-1307|Add deserialiser to handle Zoned Date Time

---

crime-commons-schemas/build.gradle

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3228)

LASB-3228: Revert to javax validation library to work with MAAT.

---

crime-commons-classes/build.gradle

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1331)

LCAM-1331-downgrade to 1.8

---

.circleci/config.yml
crime-commons-mod-schemas/build.gradle
settings.gradle

[LCAM-1354](https://dsdmoj.atlassian.net/browse/LCAM-1354)
- Created a module 'crime-commons-mod-schema'
[LCAM-1354]: https://dsdmoj.atlassian.net/browse/LCAM-1354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LCAM-1354: Created a module crime-commons-mod-schema

---

crime-commons-schemas/src/main/resources/schemas/criminalapplicationsdatastore/maat_application_external.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3244)

LASB-3244 - updated the residence type for schema between CA and CAA

---

crime-commons-classes/build.gradle
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/dto/maat_api/SolicitorCosts.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AppealType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AssessmentResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/contribution/AssessmentType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/contribution/CurrentStatus.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/meansassessment/AgeRange.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/meansassessment/IncomeType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/meansassessment/OutgoingType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/meansassessment/StatelessRequestType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/ActionType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/AssessmentResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/AssessmentType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/HardshipType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/MeanAssessmentResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/MeanAssessmentType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/RequestSource.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/Amount.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/DependantChild.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/FrequencyAmount.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/Income.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/Outgoing.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/StatelessFullResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/meansassessment/StatelessInitialResult.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1331)
Moving enum and class from respective service

LCAM-1331-add-enums

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/dto/maatapi/SolicitorCosts.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AppealType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/contribution/AssessmentType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/contribution/CurrentStatus.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/contribution/TransferStatus.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/ActionType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/AssessmentResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/AssessmentType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/HardshipType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/MeanAssessmentResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/MeanAssessmentType.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/orchestration/RequestSource.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/AppealTypeTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/contribution/CurrentStatusTest.java
crime-commons-mod-schemas/build.gradle
settings.gradle

[Link to story](https://dsdmoj.atlassian.net/browse/Lcam-1331)

Lcam-1331-add-enums-testcases

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/proceeding/MagsDecisionResult.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1331)

LCAM-1331-move-to-common-class

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AssessmentResult.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AssessmentType.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1335)

Updated Enums to be in sync with Orch service

---

crime-commons-schemas/src/main/resources/schemas/crimeapplication/common/assessmentDetail.json
crime-commons-schemas/src/main/resources/schemas/crimeapplication/common/passported.json
crime-commons-schemas/src/main/resources/schemas/criminalapplicationsdatastore/general/means.json
crime-commons-schemas/src/main/resources/schemas/criminalapplicationsdatastore/maat_application_external.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3317)

[LASB-3317] Updating LAA Crime Apply Schema with Partner details

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/MaskingPatternLayout.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/util/MaskingPatternLayoutTest.java
crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/util/MaskingPatternlayoutTest.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1320)

LCAM-1320-Obfuscate-sensitive-information

---

crime-commons-schemas/src/main/resources/schemas/crimeapplication/common/passported.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3317)

[LASB-3317] Adding jsa appointment date

---

crime-commons-schemas/src/main/resources/schemas/crimeapplication/common/assessmentDetail.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3317)

[LASB-3317]Changed Partner Frequency type

---

crime-commons-mod-schemas/build.gradle

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1368)

LCAM-1368|Restore to PROD config

---

crime-commons-mod-schemas/src/main/resources/schemas/orchestration/crown-court/common/apiCrownCourtSummary.json
crime-commons-mod-schemas/src/main/resources/schemas/proceeding/common/apiCrownCourtSummary.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1368)

LCAM-1368|Remove repOrderDecision from required fields

---

crime-commons-mod-schemas/src/main/resources/schemas/contribution/common/apiContributionSummary.json
crime-commons-mod-schemas/src/main/resources/schemas/orchestration/contribution/common/apiContributionSummary.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1220)
Removed  fileName, dateSent and dateReceived for get contribution summary

LCAM-1220-refactor contribution summary

---

crime-commons-schemas/src/main/resources/schemas/criminalapplicationsdatastore/general/means.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3422)
Adding employed schema changes

[LASB-3422] Adding employed schema changes

---

crime-commons-mod-schemas/src/main/resources/schemas/contribution/common/apiAssessment.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1457)

LCAM-1457-change Current Status enum

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/dto/maatapi/RepOrderDTO.java

new field which was needed for contributions

---

crime-commons-schemas/src/main/resources/schemas/criminalapplicationsdatastore/general/means.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3496)
Updating Employment types

[LASB-3496] Updating emp types

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/EmploymentStatus.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/evidence/IncomeEvidenceType.java

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1377)
- New enums added to the crime-commons-classes module required by the new income evidence schemas.

LCAM-1377 crime-commons-classes changes

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/dto/maatapi/FinancialAssessmentDTO.java
crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/dto/maatapi/RepOrderDTO.java

new field userCreatedEntity

---

crime-commons-schemas/src/main/resources/schemas/crimeapplication/common/initialMeansAssessment.json
crime-commons-schemas/src/main/resources/schemas/criminalapplicationsdatastore/general/means.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3501)
Updated the schema for apply to maat.

Lasb 3501 auto pop init asses notes

---

crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3573)
Adding ATIS schema

[LASB-3573] Adding ATIS schema

---

crime-commons-mod-schemas/src/main/resources/schemas/contribution/apiMaatCalculateContributionRequest.json
crime-commons-mod-schemas/src/main/resources/schemas/contribution/common/apiCrownCourtOutcome.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1576)
Renamed the fields appropriately and updated the description.
Removed redundant fields from the schema.

LCAM-1576|Tidy up Contribution schemas

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/DateUtil.java

Added utility method to DateUtil

---

crime-commons-mod-schemas/src/main/resources/schemas/orchestration/crown-court/apiUpdateApplicationRequest.json
crime-commons-mod-schemas/src/main/resources/schemas/orchestration/crown-court/common/apiCapitalEvidence.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1589)
Added new schema mapping for Crown court

LCAM-1589-Added mew mapping

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/DateUtil.java

Added utility method to get current date

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/DateUtil.java

Utility method to get current date

---

crime-commons-schemas/build.gradle

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3610)
Updated config to split ATIS schema config from CA config, allowing us to use different settings

Separate Schema Config to allow separate configurations

---

crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiCreateIncomeEvidenceRequest.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1402)
Added  applicant and partner pension amounts fields to the "Create Evidence Request".

LCAM-1402|Update Create Evidence Request to add pension amounts

---

crime-commons-samples/build.gradle
gradle.properties

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1402)
Updated the spring boot version to fix security vulnerability.

Update spring boot version to fix security vulnerability

---

README.md

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1598)
- Updated readme with details of local publishing following discussion on versioning issues.

LCAM 1598 Resolve Duplicate Version Issues

---

crime-commons-mod-schemas/src/main/resources/schemas/proceeding/request/apiUpdateCrownCourtRequest.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1628)
Created new schema for update CC outcome with financial assessment as not mandatory field

LCAM-1628-new schema

---

crime-commons-mod-schemas/src/main/resources/schemas/contribution/maat-api/ContributionRequest.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1611)
Updated the date fields in the ContributionRequest.json to match with the MAAT Court Data API.
Also fixed the id in the ContributionRequest.json.

Fix the contribution request to match the MAAT API request

---

crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3784)
Updated the crime_application_result schema with cc_rep_decision

Add CC Rep Order Decision to crime_application_result

---

crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/AssessmentResult.java

Added value for Hardship

---

crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3810)
[Link to story 2](https://dsdmoj.atlassian.net/browse/LASB-3819)
Update to add ioj appeal data and passport assessment data into the atis schema for Crime Apply

Added ioj appeal and passport fields

---

crime-commons-samples/build.gradle
gradle.properties

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1674)
Snyk has reported vulnerabilities in the current spring framework. To address these vulnerabilities, upgraded spring boot framework version and spring dependency management version.

LCAM-1674|Upgrade spring boot framework and dependency management plugins

---

crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json

[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3819)
Updated date-passport-created and ioj-appeal-date to date-time formats

Updated date-passport-created nd ioj-appeal-date to date-time formats

---

crime-commons-mod-schemas/src/main/resources/schemas/hardship/common/solicitorCosts.json

Make Disbursements Optional

---

crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiUpdateIncomeEvidenceRequest.json
crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiUpdateIncomeEvidenceResponse.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1686)
Add uplift fields on the update evidence request and response.

LCAM-1686|Add uplift fields on the update evidence request and response

---

crime-commons-mod-schemas/src/main/resources/schemas/meansassessment/maatapi/maatApiAssessmentResponse.json

[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1749)
Evidence not returning when updating financial assessment.

LCAM-1749-schema changes

---

crime-commons-samples/build.gradle
gradle.properties

[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1792)
- Upgraded version of Spring Boot to 3.4.4

LCAM 1792 Upgrade Spring Boot
