- crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/common/Constants.java
- crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/config/RestClientAutoConfiguration.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-807)
Updated the Spring WebClient builder to set maxInMemorySize to 10MB. The current default value of 2KB is causing DataBufferLimitException.
> LCAM-807: Updates to set webclient max_in_memory_size

- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/RequestBuilderUtils.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1150)
Added request builder util methods for passing transaction id in the header.
> Add request builder util methods for passing transaction id

- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/CrownCourtOutcome.java
- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/CrownCourtOutcomeType.java
- crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/enums/CrownCourtOutcomeTypeTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1105)
Changed CrownCourtOutcomeType enum to be public so it can be accessed from any project that uses this module (in particular orchestration for a fix highlighted by the integration tests) and also added unit tests for the new enum.
> LCAM 1105 Integration Tests for Means Assessment Flow

- crime-commons-spring-boot-starter-rest-client/src/main/java/uk/gov/justice/laa/crime/commons/filters/WebClientFilters.java
- crime-commons-spring-boot-starter-rest-client/src/test/java/uk/gov/justice/laa/crime/commons/filters/WebClientFiltersTest.java
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1259)
Removed Internal Server Error from the list of retriable errors defined in the handleErrorResponse filter so that they will no longer be retried.
> LCAM 1259 Remove Internal Server Error From List of Retriable Errors

- crime-commons-schemas/src/main/resources/schemas/crimeapplication/common/capitalEquity.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3244)
Updated the schema to include the new residential status field between CAA and MAAT as part of C&E work.
> LASB-3244 - add residential status to capital equity

- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/filter/mdc/AddLaaTransactionIdToMDC.java
- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/filter/mdc/AfterFilterChainClearDownMDC.java
- crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/filter/mdc/AddLaaTransactionIdToMDCTest.java
- crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/filter/mdc/AfterFilterChainClearDownMDCTest.java
Add filters to clear the MDC after each request and add the Laa-Transaction-Id to the MDC when available in the Header.
Changes include:
- New filter `AddLaaTransactionIdToMDC.java`
- New filter `AfterFilterChainClearDownMDC.java`
[Link to story - LASB-3326](https://dsdmoj.atlassian.net/browse/LASB-3326)
> LASB-3326 Add filters to clear the MDC after each request and add the Laa-Transaction-Id to the MDC when available in the Header

- .gitignore
- build.gradle
- crime-commons-classes/build.gradle
- crime-commons-mod-schemas/build.gradle
- crime-commons-schemas/build.gradle
- crime-commons-spring-boot-starter-rest-client/build.gradle
- gradle.properties
Declare all plugin version numbers in one place, the `gradle.properties` thus reducing duplication.
Also provides a means to see and update all plugin versions in a single file, making version uplift maintenance less burdensome.
**TODO** as part of a future PR, do the same for non-plugin dependency versions.
> Declare all plugin version numbers in one place gradle.properties

- crime-commons-mod-schemas/src/main/resources/schemas/hardship/maat-api/apiHardshipDetail.json
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1528)
- Added active variable to the apiHardshipDetail schema so that a value can be mapped to it form within the hardship service and then subsequently passed to maat-api to create a hardship review with active details.
> LCAM 1528 Hardship Details Not Being Set to Active on Database

- .circleci/config.yml
- crime-commons-mod-schemas/src/main/resources/schemas/hardship/common/solicitorCosts.json
[Link to story](https://dsdmoj.atlassian.net/jira/software/projects/LCAM/boards/881?selectedIssue=LCAM-1540)
- Removed the scope from the SNAPSHOT versioning as this was causing duplicate versioned SNAPSHOTs to be created following a patch release. Now the SNAPSHOT will be incremented using patch as a default. Not 100% foolproof but was a simple fix and should mean duplicates are less likely now.
- Removed estimated total from solicitors costs schema as it was causing bad request errors when calling the hardship service to create a mags hardship review with solicitors costs as the estimated total isn't calculated before the hardship service and is always null.
> LCAM 1540 Solicitors Costs Not Record on Database When Creating Hardship

- crime-commons-mod-schemas/src/main/resources/schemas/evidence/common/apiIncomeEvidenceMetadata.json
This PR adds the `applicationReceivedDate` field to the _ApiIncomeEvidenceMetadata_ schema, which is used when both creating and updating income evidence for an application as part of validation checks.
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1404)
> Add applicationReceivedDate to ApiIncomeEvidenceMetadata schema

- crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiUpdateIncomeEvidenceRequest.json
This PR adds a new `previousEvidenceDueDate` field to the _ApiUpdateIncomeEvidenceRequest_ schema, to allow evidence to be updated without the need of an additional call  to the Crime Means Assessment Service to otherwise obtain this information.
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1404)
> Add previous evidence due date to ApiUpdateIncomeEvidenceRequest schema

- crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiCreateIncomeEvidenceRequest.json
- crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiUpdateIncomeEvidenceRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1402)
Removed financial assessment id from the create and update income evidence request schemas.
> LCAM-1402|Tidy up the evidence request schemas

- crime-commons-classes/build.gradle
- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/dto/ErrorDTO.java
- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/tracing/TraceIdHandler.java
- crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/tracing/TraceIdHandlerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1609)
Moving TraceIdHandler to common classes so that this can be used in the micro-services during exception handling.
Updated ErrorDTO to allow deserialisation during exception handling.
> LCAM-1609|Moving TraceIdHandler to common classes for reuse

- crime-commons-mod-schemas/src/main/resources/schemas/proceeding/request/apiProcessRepOrderRequest.json
- crime-commons-mod-schemas/src/main/resources/schemas/proceeding/request/apiUpdateApplicationRequest.json
- crime-commons-mod-schemas/src/main/resources/schemas/proceeding/request/apiUpdateCrownCourtRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1628)
- apiUpdateCrownCourtRequest schema should extend updateApplicationRequest
- Move the following fields from apiUpdateApplicationRequest to apiUpdateCrownCourtRequest:
emstCode
incomeEvidenceReceivedDate
capitalEvidenceReceivedDate
capitalEvidence
- Financial assessment fields should be made nullable
> LCAM-1628-refactor-proceeding-schema

- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/util/SortUtils.java
- crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiCreateIncomeEvidenceResponse.json
- crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiUpdateIncomeEvidenceResponse.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1660)
Tidied up the Evidence response schemas to remove duplication and fix the required field section.
Also fixed the method declaration in the SortUitls class.
> LCAM-1660|Tidy up the Evidence response schemas

- crime-commons-mod-schemas/src/main/resources/schemas/meansassessment/maatapi/maatApiAssessmentResponse.json
- crime-commons-mod-schemas/src/main/resources/schemas/meansassessment/maatapi/maatApiUpdateAssessment.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1688)
Enhanced the MAAT API UpdateAssessment schema to include the following fields that can be updated as part of the update_income_evidence flow:
incomeUpliftApplyDate - Uplift Applied Date
incomeUpliftRemoveDate - Uplift Removed Date
evidenceReceivedDate - All income evidence received date
Also updated the MAAT API Assessment Response schema to add the missing field:
evidenceReceivedDate - Income Evidence Received Date
> LCAM-1688|Add the uplift fields to the UpdateAssessment schema

- crime-commons-mod-schemas/src/main/resources/schemas/evidence/apiUpdateIncomeEvidenceRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1728)
EvidenceDueDate is not mandatory when we update income evidence flow.
> LCAM-1728-remove-mandatory-filed

- crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3900)
As part of the enhancement to the LAA Crime Applications Adapter, we need to include the review_type field from the means_test in the API response. Added the review type field in the response
> LASB-3900 [CAA & MAAT API] Adding field review_type of the means_test to the API result

- crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3900)
As part of the enhancement to the LAA Crime Applications Adapter, we need to include the review_type field from the means_test in the API response. Added the review type field in the response
> LASB-3900 [CAA & MAAT API] Adding field passport_review_type & means_review_type of the means_test to the API result

- crime-commons-mod-schemas/src/main/resources/schemas/proceeding/request/apiDetermineMagsRepDecisionRequest.json
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1745)
Removed the required flag on 'financialAssessment' and 'passportAssessment' in 'apiDetermineMagsRepDecisionRequest.json'. These fields should not be required for this request type.
> [LCAM-1745] Update required flag in apiDetermineMagsRepDecisionRequest.json

- crime-commons-schemas/src/main/resources/schemas/atis/crime_application_result.json
[Link to story](https://dsdmoj.atlassian.net/browse/LASB-3908)
As part of the enhancement to the LAA Crime Applications Adapter, we need to include the Work Reason Code field from the means_test in the API response. Added the meansWorkReason & passportWorkReason field in the response
> LASB-3908 [CAA & MAAT API] Adding field Means & Passport Work Reasons of the means_test to the API result

- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/enums/evidence/ApplicantType.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1791)
Moving applicant type from evidence to reuse in ORC service.
> Adding new enum

- crime-commons-classes/build.gradle
- crime-commons-classes/src/main/java/uk/gov/justice/laa/crime/jackson/ZonedDateTimeDeserializer.java
- crime-commons-classes/src/test/java/uk/gov/justice/laa/crime/jackson/ZonedDateTimeDeserializerTest.java
[Link to story](https://dsdmoj.atlassian.net/browse/LCAM-1452)
The Orchestration Service needs access to the ZonedDateTimeDeserializer, which currently resides in the crime-commons-spring-boot-starter-reset-client package. This package has been removed from the Orchestration service for this ticket, so I've moved the class into the crime-commons-classes package instead. This makes sense anyway as it is a general utility class, so would belong here.
The jackson databind version has had to be upgraded as this is the version it was using in the crime-commons-spring-boot-starter-reset-client package and is required by the tests.
> [LCAM-1452] Move the ZonedDateTimeDeserializer to the crime-commons-classes package

- .circleci/config.yml
- .github/workflows/codeql-analysis.yml
- README.md
- build.gradle
- crime-commons-samples/Dockerfile
- jitpack.yml
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/LASB/boards/454?selectedIssue=LASB-4183)
- Upgraded to Java 21 for builds, pipelines and PR tasks (excluding crime-commons-schemas which I left at Java 8 as we've not upgraded the version of Java in MAAT yet).
- Removed redundant jitpack config.
> LASB 4183 Upgrade to Java 21
